-- Spell checking
--vim.keymap.set('n', '<leader>it', '<cmd>setlocal spell spelllang=it<cr>', { desc = "Set spell language to IT" })
--vim.keymap.set('n', '<leader>en', '<cmd>setlocal spell spelllang=en<cr>', { desc = "Set spell language to EN" }) -- WARN: questo va in conflitto con la keymaps per la diagnostic del lsp
